// <auto-generated />
namespace ControlTienda.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FristSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FristSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "202007282225120_FristSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
